### ISSUE TITLE
Tutorial Code cause "JSONException"

### ISSUE THREAD

**Issue by AsMidas** [TheGamingGrunts/Thunderbolt-2#3]
Error Message : 
`[Thunderbolt 2] Created new file test.json at C:\Users\Midas
2.5
derp
Exception in thread "main" me.projectx.thunderbolt2.org.json.JSONException: JSONObject["C:\\Users\\Midas"] not found.
    at me.projectx.thunderbolt2.org.json.JSONObject.get(JSONObject.java:476)
    at me.projectx.thunderbolt2.models.ThunderFile.getList(ThunderFile.java:109)
    at me.projectx.thunderbolt2.models.ThunderFile.getList(ThunderFile.java:126)
    at me.projectx.thunderbolt2.models.ThunderFile.getByteList(ThunderFile.java:141)
    at com.YouEras.BossArea.Java.main(Java.java:26)`

My Code : 

`package com.YouEras.BossArea;

import java.util.ArrayList;
import java.util.List;

import me.projectx.thunderbolt2.Thunderbolt;
import me.projectx.thunderbolt2.managers.ThunderboltManager;
import me.projectx.thunderbolt2.models.ThunderFile;

public class Java {

```
public static void main(String[] args) throws Exception {
    Thunderbolt t = new ThunderboltManager(); //Or extend ThunderboltManager

    ThunderFile tf = t.load("test", "C:\\Users\\Midas");
    List<String> l = new ArrayList<String>();
    l.add("String 1");
    l.add("String 2");
    l.add("String 3");
    tf.set("List", l);
    tf.set("Double", 2.5);
    tf.set("herp", "derp");
    tf.save();
    System.out.println(tf.getDouble("Double"));
    System.out.println(tf.getString("herp"));
    System.out.println(tf.getByteList("List"));
}
```

}`

Print : 

[Thunderbolt 2] Created new file test.json at C:/Users/Midas/Desktop
2.5
derp
Exception in thread "main" me.projectx.thunderbolt2.org.json.JSONException: JSONObject["C:/Users/Midas/Desktop"] not found.
    at me.projectx.thunderbolt2.org.json.JSONObject.get(JSONObject.java:476)
    at me.projectx.thunderbolt2.models.ThunderFile.getList(ThunderFile.java:109)
    at me.projectx.thunderbolt2.models.ThunderFile.getList(ThunderFile.java:126)
    at me.projectx.thunderbolt2.models.ThunderFile.getStringList(ThunderFile.java:130)
    at com.YouEras.BossArea.Java.main(Java.java:30)

This ERROR causes when use "getList" Methods.

**Comment by TheGamingGrunts** [comment]
This has been fixed with the latest update.
